"use strict";
/*
 * The Node implementation must reproduce Python's answers exactly.
 *
 * Ground truth is generated by scripts/emit_conformance.py. Nothing here is
 * asserted from a description of the behaviour -- the two implementations
 * disagreeing silently is the specific risk, and a test written from the same
 * misunderstanding as the code would not catch it.
 */

const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");

const { normalizeName, isBracketed, stripAuthority, splitDesignation, BloomFilter } =
  require("../src/names.js");

const fixture = JSON.parse(
  fs.readFileSync(path.join(__dirname, "conformance.json"), "utf8"));

test("normalizeName matches Python for every case", () => {
  for (const { input, expected } of fixture.normalize) {
    assert.strictEqual(normalizeName(input), expected,
      `normalizeName(${JSON.stringify(input)})`);
  }
});

test("isBracketed matches Python", () => {
  for (const { input, expected } of fixture.is_bracketed) {
    assert.strictEqual(isBracketed(input), expected, JSON.stringify(input));
  }
});

test("stripAuthority matches Python", () => {
  for (const { input, code, rank, expected } of fixture.strip_authority) {
    assert.strictEqual(stripAuthority(input, code, rank), expected,
      `stripAuthority(${JSON.stringify(input)})`);
  }
});

test("splitDesignation matches Python", () => {
  for (const { input, code, expected } of fixture.split_designation) {
    const got = splitDesignation(input, code);
    assert.deepStrictEqual(got, expected, `splitDesignation(${JSON.stringify(input)})`);
  }
});

test("bloom filter reproduces Python's bit positions", () => {
  const bf = BloomFilter.load(Buffer.from(fixture.bloom.blob_base64, "base64"));
  assert.strictEqual(bf.m, fixture.bloom.m, "m");
  assert.strictEqual(bf.k, fixture.bloom.k, "k");
  for (const [name, expected] of Object.entries(fixture.bloom.positions)) {
    const got = [...bf.positions(name)].sort((a, b) => a - b);
    assert.deepStrictEqual(got, expected, `positions(${name})`);
  }
});

test("bloom membership matches Python on every probe", () => {
  const bf = BloomFilter.load(Buffer.from(fixture.bloom.blob_base64, "base64"));
  for (const { input, expected } of fixture.bloom.probes) {
    assert.strictEqual(bf.has(input), expected, `has(${JSON.stringify(input)})`);
  }
});

test("an old-format filter is rejected with an actionable message", () => {
  const old = Buffer.alloc(24);
  old.write("BLM1", 0, "latin1");
  assert.throws(() => BloomFilter.load(old), /rebuild it/);
});
