"""Response types. Every one of them carries provenance.

The single most important property of this package: no field in any response
is generated by a language model. Every value is a lookup or a rule applied to
versioned reference data, and every value can be traced to the source and
release that produced it.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import date, datetime, timezone
from typing import Any

from .codes import Code, CodeAssignment, TaxonStatus


@dataclass(frozen=True)
class Provenance:
    """Where an assertion came from and when.

    `version` is the source's own release identifier where one exists (NCBI
    taxdump date, GBIF backbone build, ICTV MSL number). `retrieved` is when
    binomen actually fetched it, which can differ by months from the release.
    Both matter: the first tells you what the source said, the second tells you
    how stale our copy might be.
    """

    source: str
    version: str
    retrieved: str
    url: str | None = None
    license: str | None = None
    note: str | None = None

    def to_dict(self) -> dict:
        return {k: v for k, v in asdict(self).items() if v is not None}


@dataclass
class NameRecord:
    """One name as one source knows it."""

    name: str
    identifier: str | None = None
    rank: str | None = None
    authority: str | None = None
    status: TaxonStatus | None = None
    provenance: Provenance | None = None

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "identifier": self.identifier,
            "rank": self.rank,
            "authority": self.authority,
            "status": self.status.to_dict() if self.status else None,
            "provenance": self.provenance.to_dict() if self.provenance else None,
        }


@dataclass
class ChangeEvent:
    """One step in a name's history.

    `year` is frequently unknown. NCBI records that two taxids were merged but
    not when the underlying taxonomic act was published, so we distinguish
    "the year of the nomenclatural act" from "the release in which our source
    recorded it" and leave the former null rather than inferring it.
    """

    from_name: str
    to_name: str
    kind: str                      # reassignment | synonymy | merge | split | rename | elevation
    year: int | None = None
    reference: str | None = None
    provenance: Provenance | None = None
    note: str | None = None

    def to_dict(self) -> dict:
        d = {
            "from": self.from_name,
            "to": self.to_name,
            "kind": self.kind,
            "year": self.year,
            "reference": self.reference,
        }
        if self.note:
            d["note"] = self.note
        if self.provenance:
            d["provenance"] = self.provenance.to_dict()
        return d


@dataclass
class Candidate:
    """One authority's answer, when authorities disagree.

    `resolve_name` returns a list of these rather than one winner. Collapsing
    them would hide precisely the disagreement the caller needs to see -- see
    Candidozyma auris, where the split from Candida is accepted by some
    authorities and disputed in print by others.
    """

    accepted_name: str
    identifier: str | None
    rank: str | None
    authority: str | None
    status: TaxonStatus
    provenance: Provenance
    supporting_sources: list[str] = field(default_factory=list)
    dissenting_sources: list[str] = field(default_factory=list)
    argument: str | None = None
    disambiguation: str | None = None      # e.g. "Bacillus <stick insect>"
    lineage_summary: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "accepted_name": self.accepted_name,
            "identifier": self.identifier,
            "rank": self.rank,
            "authority": self.authority,
            "status": self.status.to_dict(),
            "supporting_sources": self.supporting_sources,
            "dissenting_sources": self.dissenting_sources,
            "argument": self.argument,
            "disambiguation": self.disambiguation,
            "lineage_summary": self.lineage_summary,
            "provenance": self.provenance.to_dict(),
        }


@dataclass
class Resolution:
    """The return type of `resolve_name`.

    Note what is deliberately absent: a top-level `current_name` string. If
    `contested` is true there is no single correct value for such a field, and
    providing one that callers would read on the happy path guarantees the
    disagreement gets dropped. Callers must look at `candidates`.
    """

    query: str
    matched_name: str | None
    match_type: str                       # exact | case_insensitive | fuzzy | none
    governing_code: CodeAssignment
    candidates: list[Candidate]
    contested: bool
    change_chain: list[ChangeEvent]
    provenance: list[Provenance]
    input_status: TaxonStatus | None = None
    resolution_id: str | None = None
    warnings: list[str] = field(default_factory=list)
    consulted_sources: list[str] = field(default_factory=list)
    as_of: str = field(default_factory=lambda: date.today().isoformat())

    def to_dict(self) -> dict:
        return {
            "query": self.query,
            "matched_name": self.matched_name,
            "match_type": self.match_type,
            "governing_code": self.governing_code.to_dict(),
            "input_status": self.input_status.to_dict() if self.input_status else None,
            "contested": self.contested,
            "candidates": [c.to_dict() for c in self.candidates],
            "change_chain": [e.to_dict() for e in self.change_chain],
            "consulted_sources": self.consulted_sources,
            "warnings": self.warnings,
            "resolution_id": self.resolution_id,
            "as_of": self.as_of,
            "provenance": [p.to_dict() for p in self.provenance],
        }


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def jsonable(obj: Any) -> Any:
    """Recursively convert dataclasses/enums to plain JSON types."""
    if hasattr(obj, "to_dict"):
        return jsonable(obj.to_dict())
    if isinstance(obj, dict):
        return {k: jsonable(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [jsonable(v) for v in obj]
    if isinstance(obj, Code):
        return obj.value
    return obj
