"""Response types. Every one of them carries provenance.

The single most important property of this package: no field in any response
is generated by a language model. Every value is a lookup or a rule applied to
versioned reference data, and every value can be traced to the source and
release that produced it.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import date, datetime, timezone
from typing import Any

from .codes import Code, CodeAssignment, TaxonStatus


@dataclass(frozen=True)
class Provenance:
    """Where an assertion came from and when.

    `version` is the source's own release identifier where one exists (NCBI
    taxdump date, GBIF backbone build, ICTV MSL number). `retrieved` is when
    binomen actually fetched it, which can differ by months from the release.
    Both matter: the first tells you what the source said, the second tells you
    how stale our copy might be.
    """

    source: str
    version: str
    retrieved: str
    url: str | None = None
    license: str | None = None
    note: str | None = None

    def to_dict(self) -> dict:
        return {k: v for k, v in asdict(self).items() if v is not None}


@dataclass
class NameRecord:
    """One name as one source knows it."""

    name: str
    identifier: str | None = None
    rank: str | None = None
    authority: str | None = None
    status: TaxonStatus | None = None
    provenance: Provenance | None = None

    def to_dict(self) -> dict:
        d = {"name": self.name}
        for k, v in (("identifier", self.identifier), ("rank", self.rank),
                     ("authority", self.authority)):
            if v:
                d[k] = v
        if self.status:
            d["status"] = self.status.to_dict()
        if self.provenance:
            d["provenance"] = self.provenance.to_dict()
        return d


@dataclass
class ChangeEvent:
    """One step in a name's history.

    `year` is frequently unknown. NCBI records that two taxids were merged but
    not when the underlying taxonomic act was published, so we distinguish
    "the year of the nomenclatural act" from "the release in which our source
    recorded it" and leave the former null rather than inferring it.
    """

    from_name: str
    to_name: str
    kind: str                      # reassignment | synonymy | merge | split | rename | elevation
    year: int | None = None
    reference: str | None = None
    provenance: Provenance | None = None
    note: str | None = None

    def to_dict(self) -> dict:
        """Null fields are omitted, not emitted.

        `"year": null, "reference": null` on every event was pure overhead --
        absence already means unknown. The distinction that matters (we do not
        know the year vs. we are guessing at it) is carried by the top-level
        `as_of_answerable` flag and the accompanying warning, not by a null.
        """
        d = {"from": self.from_name, "to": self.to_name, "kind": self.kind}
        if self.year is not None:
            d["year"] = self.year
        if self.reference:
            d["reference"] = self.reference
        if self.note:
            d["note"] = self.note
        if self.provenance:
            d["provenance"] = self.provenance.to_dict()
        return d


@dataclass
class Candidate:
    """One authority's answer, when authorities disagree.

    `resolve_name` returns a list of these rather than one winner. Collapsing
    them would hide precisely the disagreement the caller needs to see -- see
    Candidozyma auris, where the split from Candida is accepted by some
    authorities and disputed in print by others.
    """

    accepted_name: str
    identifier: str | None
    rank: str | None
    authority: str | None
    status: TaxonStatus
    provenance: Provenance
    supporting_sources: list[str] = field(default_factory=list)
    dissenting_sources: list[str] = field(default_factory=list)
    argument: str | None = None
    disambiguation: str | None = None      # e.g. "Bacillus <stick insect>"
    lineage_summary: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        """Non-null fields only, and provenance by source name.

        The full provenance block is repeated once at the top level of the
        response; naming it here is enough to attribute the candidate without
        duplicating the version, URL and license per candidate.
        """
        d = {
            "accepted_name": self.accepted_name,
            "status": self.status.to_dict(),
            "sources": self.supporting_sources,
        }
        for k, v in (("identifier", self.identifier), ("rank", self.rank),
                     ("authority", self.authority), ("argument", self.argument),
                     ("disambiguation", self.disambiguation)):
            if v:
                d[k] = v
        if self.dissenting_sources:
            d["dissenting_sources"] = self.dissenting_sources
        if self.lineage_summary:
            d["lineage_summary"] = self.lineage_summary
        return d


@dataclass
class Resolution:
    """The return type of `resolve_name`.

    Note what is deliberately absent: a top-level `current_name` string. If
    `contested` is true there is no single correct value for such a field, and
    providing one that callers would read on the happy path guarantees the
    disagreement gets dropped. Callers must look at `candidates`.
    """

    query: str
    matched_name: str | None
    match_type: str                       # exact | case_insensitive | fuzzy | none
    governing_code: CodeAssignment
    candidates: list[Candidate]
    contested: bool
    change_chain: list[ChangeEvent]
    provenance: list[Provenance]
    input_status: TaxonStatus | None = None
    resolution_id: str | None = None
    warnings: list[str] = field(default_factory=list)
    consulted_sources: list[str] = field(default_factory=list)
    as_of: str = field(default_factory=lambda: date.today().isoformat())

    def to_dict(self) -> dict:
        d = {
            "query": self.query,
            "governing_code": self.governing_code.to_dict(),
            "candidates": [c.to_dict() for c in self.candidates],
            "provenance": [p.to_dict() for p in self.provenance],
        }
        # Only carried when they say something. `contested` and `match_type`
        # in particular were emitted on every response to say "false" and
        # "exact", which is the default a caller already assumes.
        if self.contested:
            d["contested"] = True
        if self.match_type != "exact":
            d["match_type"] = self.match_type
        if self.matched_name and self.matched_name != self.query:
            d["matched_name"] = self.matched_name
        if self.input_status:
            d["input_status"] = self.input_status.to_dict()
        if self.change_chain:
            d["change_chain"] = [e.to_dict() for e in self.change_chain]
        if self.warnings:
            d["warnings"] = self.warnings
        if self.resolution_id:
            d["resolution_id"] = self.resolution_id
        return d


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def jsonable(obj: Any) -> Any:
    """Recursively convert dataclasses/enums to plain JSON types."""
    if hasattr(obj, "to_dict"):
        return jsonable(obj.to_dict())
    if isinstance(obj, dict):
        return {k: jsonable(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [jsonable(v) for v in obj]
    if isinstance(obj, Code):
        return obj.value
    return obj
