#!/usr/bin/env python3
"""Emit the cross-language conformance fixture.

binomen has two implementations of the same lookup: Python (the resolver, the
eval harness) and Node (the shipped extension). They must agree exactly on two
things, or they will disagree about what a name *means*:

  normalize_name   the lookup key. One character-class difference and a name
                   resolves in one implementation and not the other.
  bloom positions  the Bloom filters are built by Python and read by Node. A
                   different hash, byte order or index derivation makes every
                   membership test wrong -- and wrong in the direction of
                   "no record of this name", which reads as a legitimate
                   negative result.

Reimplementing from a prose description and hoping is exactly the mistake this
project catalogues. So Python emits ground truth and Node replays it.

    python scripts/emit_conformance.py > node/test/conformance.json
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from binomen.bloom import BloomFilter  # noqa: E402
from binomen.build.build_index import (  # noqa: E402
    is_bracketed,
    normalize_name,
    split_designation,
    strip_authority,
)

# Chosen to cover every branch and every trap found the hard way.
NAMES = [
    "Escherichia coli",
    "Clostridium difficile",
    "Clostridioides difficile",
    "  Clostridioides   difficile  ",          # whitespace collapse
    "CLOSTRIDIOIDES DIFFICILE",                # case fold
    "[Clostridium] difficile",                 # NCBI misplacement brackets
    "[Ruminococcus] gnavus",
    "(Clostridium) difficile",                 # parentheses folded too
    "Clostridium difficile (Hall and O'Toole 1935) Prevot 1938 (Approved Lists 1980)",
    "Candida auris Satoh & Makimura, 2009",
    "Bacillus subtilis subsp. spizizenii Nakamura et al. 1999",
    "Rosa x damascena Mill.",
    "Rosa × damascena",                        # unicode hybrid sign
    "Nätterö bacterium",                       # combining marks
    "Æsculus hippocastanum",                   # ligature via NFKD
    "Candidatus Liberibacter asiaticus",
    "Candidatus Liberibacter asiaticus psy62",
    "Clostridioides difficile 630",
    "Escherichia coli O157:H7 str. Sakai",
    "Salmonella enterica subsp. enterica serovar Typhi",
    "Bacillus subtilis ATCC 6051",
    "Homo sapiens Linnaeus, 1758",
    "Severe acute respiratory syndrome coronavirus 2",
    "Human alphaherpesvirus 1",
    "Influenza A virus (A/Puerto Rico/8/1934(H1N1))",
    "SEPT2",
    "",
    "   ",
]

# A filter whose exact bit pattern Node must reproduce, plus probes that must
# come back with identical answers on both sides.
BLOOM_MEMBERS = [
    "escherichia coli", "homo sapiens", "bacillus subtilis",
    "saccharomyces cerevisiae", "arabidopsis thaliana", "danio rerio",
    "drosophila melanogaster", "mycobacterium tuberculosis",
]
BLOOM_PROBES = BLOOM_MEMBERS + [
    "clostridium difficile", "not a real name at all", "zzzz qqqq", "escherichia col",
    "Escherichia coli",  # unnormalized: must be a miss, keys are normalized
]


def main() -> int:
    bf = BloomFilter.sized(len(BLOOM_MEMBERS), 0.001)
    for m in BLOOM_MEMBERS:
        bf.add(m)

    out = {
        "_comment": "Generated by scripts/emit_conformance.py. Ground truth from the "
                    "Python implementation; the Node implementation must reproduce it "
                    "exactly. Regenerate whenever normalization or the filter changes.",
        "normalize": [{"input": n, "expected": normalize_name(n)} for n in NAMES],
        "is_bracketed": [{"input": n, "expected": is_bracketed(n)} for n in NAMES],
        "strip_authority": [
            {"input": n, "code": None, "rank": "species",
             "expected": strip_authority(n, None, "species")} for n in NAMES],
        "split_designation": [
            {"input": n, "code": None, "expected": list(split_designation(n) or []) or None}
            for n in NAMES],
        "bloom": {
            "m": bf.m,
            "k": bf.k,
            "n": bf.n,
            "blob_base64": __import__("base64").b64encode(bf.dumps()).decode(),
            "positions": {m: sorted(bf._positions(m)) for m in BLOOM_MEMBERS[:3]},
            "probes": [{"input": p, "expected": p in bf} for p in BLOOM_PROBES],
        },
    }
    json.dump(out, sys.stdout, indent=2, ensure_ascii=False)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
